#!/usr/bin/env python3
"""
Fortune Generator - A sassy goose fortune teller
Generates introspective fortunes with ASCII art
"""

import os
import shutil
from datetime import datetime

# Introspective fortunes from the mystical fortune teller
FORTUNES = [
    "The path you seek begins with a single step... but remember, even geese know when to turn back.",
    "Your reflection holds more wisdom than you realize. Listen to the quiet voice within.",
    "Change approaches like the tide. Will you swim with it, or become the shore that breaks it?",
    "The answers you seek are not in the stars, but in the choices you make today.",
    "Sometimes the greatest journey is the one inward. What will you discover in your own depths?",
    "Your strength lies not in never falling, but in how gracefully you rise each time.",
    "The mirror shows more than your face—it reveals the soul you're becoming.",
    "Doubt is merely wisdom in disguise, waiting for you to recognize its value.",
    "The future is not written in stone, but in the ink of your daily actions.",
    "True freedom comes from understanding what truly matters to your heart."
]

# Sassy goose ASCII art
GOOSE_ART = """
    __      __
   /  \\    /  \\
  |    \\__/    |
  |  o      o  |
  |     <      |
  |   \\____/   |
   \\  \\    /  /
    \\  \\__/  /
     \\______/
    _/      \\_
   /          \\
  |  SASSY   |
  |   GOOSE  |
  \\__________/
"""

def generate_fortune():
    """Generate a random introspective fortune"""
    import random
    return random.choice(FORTUNES)

def create_fortune_display():
    """Create the full fortune display with border, fortune, divider, and goose"""
    fortune = generate_fortune()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Create the border and content
    border_top = "╔" + "═" * 58 + "╗"
    border_mid = "║" + " " * 58 + "║"
    border_bot = "╚" + "═" * 58 + "╝"
    divider = "║" + "─" * 58 + "║"
    
    # Build the fortune display
    lines = []
    lines.append(border_top)
    lines.append("║" + " " * 20 + "🔮 FORTUNE TELLER 🔮" + " " * 15 + "║")
    lines.append("║" + " " * 17 + f"Introspective Wisdom - {timestamp}" + " " * 8 + "║")
    lines.append(border_mid)
    lines.append("║" + " " * 58 + "║")
    lines.append("║" + " " * 5 + fortune + " " * (58 - len(fortune) - 5) + "║")
    lines.append("║" + " " * 58 + "║")
    lines.append(divider)
    lines.append("║" + " " * 58 + "║")
    
    # Add the goose art with proper padding
    goose_lines = GOOSE_ART.strip().split('\n')
    for line in goose_lines:
        padded_line = line.center(58)
        lines.append("║" + padded_line + "║")
    
    lines.append("║" + " " * 58 + "║")
    lines.append("║" + " " * 18 + "Remember: You are the answer" + " " * 14 + "║")
    lines.append(border_bot)
    
    return '\n'.join(lines)

def save_fortune(content):
    """Save the fortune to fortune.md, backing up existing file if needed"""
    fortune_path = "fortune.md"
    old_dir = "old"
    
    # Check if fortune.md exists and move it to old folder
    if os.path.exists(fortune_path):
        # Create old directory if it doesn't exist
        os.makedirs(old_dir, exist_ok=True)
        
        # Move existing fortune.md to old folder with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        old_path = os.path.join(old_dir, f"fortune_{timestamp}.md")
        shutil.move(fortune_path, old_path)
        print(f"Backed up existing fortune.md to: {old_path}")
    
    # Write new fortune to file
    with open(fortune_path, 'w', encoding='utf-8') as f:
        f.write("# 🔮 Your Introspective Fortune 🔮\n\n")
        f.write("Generated by the Sassy Goose Fortune Teller\n\n")
        f.write("```\n")
        f.write(content)
        f.write("\n```\n")
    
    print(f"Fortune saved to: {fortune_path}")

def main():
    """Main function to generate and save fortune"""
    print("🔮 Consulting the mystical Sassy Goose Fortune Teller...")
    print()
    
    # Generate the fortune display
    fortune_display = create_fortune_display()
    
    # Display to console
    print(fortune_display)
    print()
    
    # Save to file
    save_fortune(fortune_display)
    
    print("\n✨ Your fortune has been revealed! ✨")

if __name__ == "__main__":
    main()
