#!/usr/bin/env python3
"""
Fortune Generator - A wise sassy goose fortune teller
Generates fortunes with ASCII art and saves to fortune.md
"""

import os
import shutil
from datetime import datetime

# Wise fortunes from the sassy goose
FORTUNES = [
    "The path you seek is not the one you planned, but the one you create with each step.",
    "Wisdom comes not from knowing all answers, but from asking better questions.",
    "A sassy goose knows: the best predictions are the ones you make happen yourself.",
    "The stars align not by chance, but by the gravity of your own determination.",
    "True fortune favors not the lucky, but the bold who dare to flap their wings.",
    "Like a goose in flight, your journey may be turbulent, but the destination is yours.",
    "The future is a pond you haven't ruffled yet—make your splash count.",
    "Wisdom whispers: sometimes the detour is where the treasure hides.",
    "A wise goose knows that even the longest flight begins with a single honk.",
    "The universe conspires with those who dare to waddle toward their dreams."
]

# ASCII art of a sassy goose
SASSY_GOOSE = """
      __
     /  \\
    |    |
    |    |___
    |    |   |
    |    |   |
    |    |   |
    |    |   |
    |    |___|
    |    |   |
    |    |   |
    |    |   |
    |    |   |
    |    |___|
     \\  /
      \\/
    (SASSY GOOSE)
"""

# Divider between goose and fortune
DIVIDER = "=" * 50

# Border character
BORDER_CHAR = "#"


def create_border(content, width=52):
    """Create an ASCII border around content."""
    border_top = BORDER_CHAR * width
    border_bottom = BORDER_CHAR * width
    
    lines = content.split('\n')
    bordered_lines = []
    
    for line in lines:
        # Pad line to fit within border
        padded_line = line.ljust(width - 2)
        bordered_lines.append(f"{BORDER_CHAR} {padded_line} {BORDER_CHAR}")
    
    return f"{border_top}\n" + "\n".join(bordered_lines) + f"\n{border_bottom}"


def generate_fortune():
    """Generate a wise fortune from the sassy goose."""
    import random
    return random.choice(FORTUNES)


def main():
    # Get a wise fortune
    fortune = generate_fortune()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Build the fortune content
    content_lines = [
        "",
        "✨ WISE FORTUNE FROM THE SASSY GOOSE ✨",
        "",
        SASSY_GOOSE,
        DIVIDER,
        "",
        f"🔮 Your Fortune ({timestamp}):",
        "",
        f"   {fortune}",
        "",
        "   ~ The Sassy Goose, Keeper of Wisdom",
        "",
        "   Remember: Honk if you agree!",
        ""
    ]
    
    content = "\n".join(content_lines)
    
    # Create bordered output
    bordered_content = create_border(content)
    
    # Add markdown header
    markdown_content = f"""# 🦢 Sassy Goose Fortune

{bordered_content}

*Generated by the wise sassy goose fortune teller*
"""
    
    # Handle existing fortune.md file
    fortune_file = "fortune.md"
    old_folder = "old"
    
    if os.path.exists(fortune_file):
        # Create old folder if it doesn't exist
        os.makedirs(old_folder, exist_ok=True)
        
        # Move existing file to old folder with timestamp
        timestamp_suffix = datetime.now().strftime("%Y%m%d_%H%M%S")
        old_filename = f"fortune_{timestamp_suffix}.md"
        old_path = os.path.join(old_folder, old_filename)
        
        shutil.move(fortune_file, old_path)
        print(f"Moved existing fortune.md to {old_path}")
    
    # Write new fortune to fortune.md
    with open(fortune_file, 'w') as f:
        f.write(markdown_content)
    
    print(f"Fortune generated and saved to {fortune_file}")
    print("\n" + bordered_content)


if __name__ == "__main__":
    main()
