#!/usr/bin/env python3
"""
Fortune Generator - A sassy goose delivers introspective wisdom
"""

import os
import shutil
from datetime import datetime

# Introspective fortunes
FORTUNES = [
    "The path you seek is not ahead, but within. What you've been running from has been waiting to be understood.",
    "Your doubts are not enemies—they are guardians of the threshold. Listen to what they protect.",
    "The question you're afraid to ask is the one that will set you free.",
    "Yesterday's wounds have become today's wisdom. Honor the journey, not just the destination.",
    "You are not lost; you are exploring. The map will reveal itself as you walk.",
    "The mirror shows more than your face—it reflects the stories you tell yourself. Which ones serve you?",
    "Silence is not empty; it is full of answers you haven't learned to hear yet.",
    "Your shadow holds treasures your light has yet to discover. Embrace both.",
    "The weight you carry is not meant to break you—it is meant to anchor you to what matters.",
    "Growth feels like falling until you realize you're learning to fly."
]

# Sassy goose ASCII art
GOOSE_ART = """
      __
     /  \\
    |    |
    |    |
    |    |
    |    |
    |    |
    |    |
    |    |
   /      \\
  /        \\
 /          \\
/____________\\
"""

# Alternative sassy goose with attitude
GOOSE_ART_SASSY = """
      __
     /  \\
    | o  |
    |    |
    |    |
    |    |
    |    |
    |    |
    |    |
   /      \\
  /        \\
 /          \\
/____________\\
   (sassy)
"""

# Even sassier goose
GOOSE_ART_FINAL = """
      __
     /  \\
    | >_<|
    |    |
    |    |
    |    |
    |    |
    |    |
    |    |
   /      \\
  /        \\
 /          \\
/____________\\
  *glare*
"""

def get_fortune():
    """Select a random introspective fortune."""
    import random
    return random.choice(FORTUNES)

def create_fortune_display():
    """Create the visually appealing fortune display with ASCII art."""
    fortune = get_fortune()
    
    # Calculate border width based on content
    lines = [
        "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨",
        "✨                    FORTUNE TELLER                     ✨",
        "✨                    ~ Introspective ~                  ✨",
        "✨" + " " * 58 + "✨",
        "✨" + " " * 20 + "YOUR FORTUNE:" + " " * 23 + "✨",
        "✨" + " " * 58 + "✨",
    ]
    
    # Add fortune text wrapped to fit
    max_width = 54
    words = fortune.split()
    current_line = ""
    for word in words:
        if len(current_line) + len(word) + 1 <= max_width:
            if current_line:
                current_line += " " + word
            else:
                current_line = word
        else:
            lines.append("✨ " + current_line.ljust(max_width) + " ✨")
            current_line = word
    if current_line:
        lines.append("✨ " + current_line.ljust(max_width) + " ✨")
    
    lines.append("✨" + " " * 58 + "✨")
    lines.append("✨" + "─" * 58 + "✨")
    lines.append("✨" + " " * 58 + "✨")
    lines.append("✨" + " " * 15 + "THE SASSY GOOSE SAYS:" + " " * 14 + "✨")
    lines.append("✨" + " " * 58 + "✨")
    
    # Add goose art with padding
    goose_lines = GOOSE_ART_FINAL.strip().split('\n')
    for goose_line in goose_lines:
        lines.append("✨ " + goose_line.center(56) + " ✨")
    
    lines.append("✨" + " " * 58 + "✨")
    lines.append("✨" + "─" * 58 + "✨")
    lines.append("✨" + " " * 18 + f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} " + " " * 16 + "✨")
    lines.append("✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨")
    
    return '\n'.join(lines)

def main():
    """Main function to generate and save fortune."""
    output_file = "fortune.md"
    old_folder = "old"
    
    # Check if fortune.md exists and move it to old folder
    if os.path.exists(output_file):
        os.makedirs(old_folder, exist_ok=True)
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        old_name = f"{old_folder}/fortune_{timestamp}.md"
        shutil.move(output_file, old_name)
        print(f"Moved existing fortune.md to {old_name}")
    
    # Generate the fortune display
    fortune_display = create_fortune_display()
    
    # Create markdown content with the ASCII art
    markdown_content = f"""# 🦢 Daily Fortune 🦢

```
{fortune_display}
```

---

*Generated by the Sassy Goose Fortune Teller*
"""
    
    # Write to fortune.md
    with open(output_file, 'w') as f:
        f.write(markdown_content)
    
    print(f"Fortune generated and saved to {output_file}")
    print("\n" + "=" * 50)
    print("Here's your fortune:")
    print("=" * 50)
    print(fortune_display)

if __name__ == "__main__":
    main()
